services:
  dashboardKanbanFE:
    image: dashboard-kanban-fe
    ports:
      - "4200:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - dashboardKanbanBE
  dashboardKanbanBE:
    image: dashboard-kanban-be
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://dashboardKanbanDB:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    depends_on:
      - dashboardKanbanDB
  dashboardKanbanDB:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - ./backend/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
volumes:
  postgres_data:
