services:
  dashboardKanbanFE:
    image: dashboard-kanban-fe
    ports:
      - "4200:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - dashboardKanbanBE
  dashboardKanbanBE:
    image: dashboard-kanban-be
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://dashboardKanbanDB:3306/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    depends_on:
      - dashboardKanbanDB
  dashboardKanbanDB:
    image: mysql:8.0.36
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
    restart: always
    volumes:
      - ./backend/db.sql:/docker-entrypoint-initdb.d/db.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
volumes:
  mysql_data:
