# render.yaml - VERSIÓN CORREGIDA

services:
  - type: web
    name: dashboard-kanban-be
    env: docker
    buildCommand: "ls -laR"
    repo: https://github.com/Artikunazo/dashboard-kanban-v2
    dockerContext: ./backend
    dockerfilePath: Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: dashboard-kanban-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: dashboard-kanban-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dashboard-kanban-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: dashboard-kanban-db
          property: database
    plan: free

  - type: web
    name: dashboard-kanban-fe
    env: docker
    repo: https://github.com/Artikunazo/dashboard-kanban-v2
    dockerContext: ./frontend
    dockerfilePath: Dockerfile
    # La línea 'buildCommand' se eliminó. Tu Dockerfile debe encargarse de hacer
    # 'npm install' y 'npm run build:render' con comandos RUN.
    envVars:
      - key: API_URL
        fromService:
          type: web
          name: dashboard-kanban-be
          property: url
    plan: free

databases:
  - name: dashboard-kanban-db
    databaseName: kanban_db
    user: kanban_user
    plan: free
    ipAllowList: []